spring:
    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: local

    datasource:
        url: jdbc:mysql://${MY_SQL.HOST}:${MY_SQL.PORT}/${MY_SQL.DATABASE}?useSSL=false&serverTimezone=Asia/Seoul
        username: ${DB.USERNAME}
        password: ${DB.PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${JPA.DDL_AUTO}
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ${KAKAO.CLIENT.ID}
                        client-secret: ${KAKAO.CLIENT.SECRET}
                        client-name: kakao
                        client-authentication-method: client_secret_post # access token 발급시 client_id, client_secret을 post로 보낸다.
                        redirect-uri: "{baseUrl}/auth/login/oauth2/code/{registrationId}"
                        authorization-grant-type: authorization_code
                        scope:
                            - account_email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

# JWT
jwt:
    token:
        access:
            expiration: 86_400_000 # 1일

# SQL log
logging:
    level:
        p6spy: DEBUG
decorator:
    datasource:
        p6spy:
            enable-logging: true
# SQL log

# cors
allowed-origin: ${DOMAIN}
# cors

# domain
domain: ${DOMAIN}
